app:
  environment:
    PRIVATE_KEY_PATH: /home/lesytruong/projects/Noddit/server/keys/private.pem
    PUBLIC_KEY_PATH: /home/lesytruong/projects/Noddit/server/keys/public.pem
    RBAC_PATH: /home/lesytruong/projects/Noddit/server/rbac-config/rbac_model.conf

